/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type BN from "bn.js";
import type { ContractOptions } from "web3-eth-contract";
import type { EventLog } from "web3-core";
import type { EventEmitter } from "events";
import type {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface CeloEduMarketplace extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): CeloEduMarketplace;
  clone(): CeloEduMarketplace;
  methods: {
    addCourse(
      _title: string,
      _description: string,
      _author: string,
      _image: string,
      _price: number | string | BN
    ): NonPayableTransactionObject<void>;

    buyCourse(_index: number | string | BN): PayableTransactionObject<void>;

    completeCourse(
      _index: number | string | BN
    ): PayableTransactionObject<void>;

    getCourse(_index: number | string | BN): NonPayableTransactionObject<{
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
      5: string;
      6: string;
    }>;

    getCourseLearners(
      _index: number | string | BN
    ): NonPayableTransactionObject<[string, boolean][]>;

    isBoughtCourse(
      _index: number | string | BN
    ): NonPayableTransactionObject<boolean>;

    isCompleteCourse(
      _index: number | string | BN
    ): NonPayableTransactionObject<boolean>;

    totalCourses(): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
